version: '3'
services:
    # influxdb:
    #     image: influxdb:latest
    #     ports:
    #         - '8086:8086'
    #     volumes:
    #         - ./influxdb/:/var/lib/influxdb
    #     environment:
    #         - INFLUXDB_DB=db0
    #         - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
    #         - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    # chronograf:
    #     image: chronograf:latest
    #     ports:
    #         - '127.0.0.1:8888:8888'
    #     volumes:
    #         - ./chronograf/:/var/lib/chronograf
    #     depends_on:
    #         - influxdb
    #     environment:
    #         - INFLUXDB_URL=http://influxdb:8086
    #         - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
    #         - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

    mysql:
        user: "$UID:$GID"
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./tmp/:/var/lib/mysql
        restart: always
        environment:
            - TZ=Asia/Jerusalem
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    grafana:
        image: grafana/grafana:latest
        user: "$UID:$GID"
        ports:
            - '3000:3000'
        volumes:
            - ./tmp/grafana/:/var/lib/grafana
            - ./tmp/grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - mysql
        environment:
            - TZ=Asia/Jerusalem
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - GF_RENDERING_SERVER_URL=http://renderer:8081/render
            - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
            - GF_LOG_FILTERS=rendering:debug

    emqtt:
        user: "$UID:$GID"
        image: raymondmm/emqtt
        ports:
            - '1883:1883'
            - '8083:8083'
            - '8084:8084'
            - '18083:18083'
        environment:
            - TZ=Asia/Jerusalem
            - 'EMQ_NAME=emq'
            - 'EMQ_NODE__COOKIE=ef16498f66804df1cc6172f6996d5492'
            - 'EMQ_WAIT_TIME=60'

    # node:
    #     build: ./node/
    #     command: yarn start
    #     restart: on-failure:10
    #     volumes:
    #         - ./node/exporter/index.js:/usr/app/index.js:rw
    #     depends_on:
    #         - emqtt
    #         - influxdb
    #     links:
    #         - influxdb:database
    #         - emqtt:emqtt-broker
    #         - mysql:mysql

    renderer:
        image: grafana/grafana-image-renderer:latest
        ports:
            - 8081

    node-microservices:
        user: "$UID:$GID"
        image: node:12-alpine
        restart: on-failure:10
        volumes:
            - ./microservices:/app/
        ports:
            - '9000:9000'
            - '6000:6000'
        depends_on:
            - grafana
            - emqtt
            - mysql
        links:
            - emqtt:emqtt-broker
            - mysql:mysql
        environment:
            - TZ=Asia/Jerusalem
        command:
            [
                'ash',
                '-c',
                'npm install pm2 -g && cd /app/ && yarn install --production && pm2 start && pm2 logs -f',
            ]
