version: '3'
services:
    mysql:
        user: '$UID:$GID'
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./tmp/mysql/:/var/lib/mysql
        restart: always
        environment:
            - TZ=Asia/Jerusalem
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    grafana:
        image: grafana/grafana:latest
        user: '$UID:$GID'
        ports:
            - '3000:3000'
        volumes:
            - ./tmp/grafana/:/var/lib/grafana
            - ./tmp/grafana-provisioning/:/etc/grafana/provisioning
            - ./tmp/config/grafana.ini:/etc/grafana/grafana.ini:z
            - ./tmp/config/dashboards:/var/lib/grafana/dashboards
            - ./tmp/config/datasources:/etc/grafana/datasources
            - ./tmp/config/plugins:/var/lib/grafana/plugins
        depends_on:
            - mysql
        environment:
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - GF_RENDERING_SERVER_URL=http://renderer:8081/render
            - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
            - GF_LOG_FILTERS=rendering:debug
        labels:
            - 'traefik.http.routers.grafana.rule=Host(`sol-iot.tk`) && PathPrefix(`/grafana`)'
            - 'traefik.http.routers.grafanaApi.rule=PathPrefix(`api`)'
            - 'traefik.http.routers.grafana.entrypoints=frontendSecure'
            - 'traefik.http.routers.grafanaApi.entrypoints=frontend'
            - 'traefik.http.routers.grafana.tls.certresolver=myresolver'

    emqtt:
        user: '$UID:$GID'
        image: raymondmm/emqtt
        ports:
            - '1883:1883'
            - '8083:8083'
            - '8084:8084'
            - '18083:18083'
        environment:
            - TZ=Asia/Jerusalem
            - 'EMQ_NAME=emq'
            - 'EMQ_NODE__COOKIE=ef16498f66804df1cc6172f6996d5492'
            - 'EMQ_WAIT_TIME=60'

    frontend:
        stdin_open: true
        image: node:12-alpine
        entrypoint:
            [
                'ash',
                '-c',
                'cd /app/ && ls -la && yarn && PORT=9000 npm start && sleep 10',
            ]
        volumes:
            - ./microservices/control-panel-frontend/:/app/
        ports:
            - '9000:9000'
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.frontend.rule=Host(`sol-iot.tk`)' #  || Host(`solgraph.ddnsking.com`)
            - 'traefik.http.routers.frontend.entrypoints=frontendSecure'
            - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
        restart: always

    nats:
        image: nats
        ports:
            - '4222:4222'
            - '6222:6222'
            - '8222:8222'

    microservices:
        user: '$UID:$GID'
        image: node:12-alpine
        volumes:
            - ./microservices:/app/
        ports:
            - '6000:6000'
        depends_on:
            - grafana
            - emqtt
            - mysql
        restart: always
        links:
            - emqtt:emqtt-broker
            - mysql:mysql
        environment:
            - GRAPHANA_API_KEY=Bearer ${GRAFANA_API_KEY}
            - TZ=Asia/Jerusalem
        command:
            [
                'ash',
                '-c',
                'npm install pm2 -g && cd /app/ && yarn install --production && pm2 start && pm2 logs -f',
            ]

    traefik:
        image: 'traefik:v2.3'
        command:
            #- "--log.level=DEBUG"
            - '--api.insecure=true'
            - '--providers.docker=true'
            - '--providers.docker.exposedbydefault=true'
            - '--entrypoints.frontend.address=:80'
            - '--pilot.token=992e4f49-d0f5-4db9-8175-7ad36acca939'
            - '--entrypoints.frontendSecure.address=:443'
            #- '--entrypoints.frontend.http.redirections.entryPoint.to=frontendSecure'
            - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
            #- '--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
            - '--certificatesresolvers.myresolver.acme.email=genesys225@gmail.com'
            - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'

        volumes:
            - './letsencrypt:/letsencrypt'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
