version: '3'
services:
    mysql:
        user: '$UID:$GID'
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./tmp/mysql/:/var/lib/mysql
        restart: always
        environment:
            - TZ=Asia/Jerusalem
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    grafana:
        image: grafana/grafana:latest
        user: '$UID:$GID'
        ports:
            - '3000:3000'
        volumes:
            - ./tmp/grafana/:/var/lib/grafana
            - ./tmp/grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
            - mysql
        environment:
            - TZ=Asia/Jerusalem
            - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
            - GF_RENDERING_SERVER_URL=http://renderer:8081/render
            - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
            - GF_LOG_FILTERS=rendering:debug
    emqtt:
        user: '$UID:$GID'
        image: raymondmm/emqtt
        ports:
            - '1883:1883'
            - '8083:8083'
            - '8084:8084'
            - '18083:18083'
        environment:
            - TZ=Asia/Jerusalem
            - 'EMQ_NAME=emq'
            - 'EMQ_NODE__COOKIE=ef16498f66804df1cc6172f6996d5492'
            - 'EMQ_WAIT_TIME=60'
    frontend:
        stdin_open: true
        image: node:12-alpine
        entrypoint:
            ['ash', '-c', 'cd /app/ && ls -la && yarn && PORT=9000 npm start && sleep 10']
        volumes:
            - ./microservices/control-panel-frontend/:/app/
        ports:
            - '9000:9000'
        restart: always
    microservices:
        user: '$UID:$GID'
        image: node:12-alpine
        volumes:
            - ./microservices:/app/
        ports:
            - '6000:6000'
        depends_on:
            - grafana
            - emqtt
            - mysql
        links:
            - emqtt:emqtt-broker
            - mysql:mysql
        environment:
            - TZ=Asia/Jerusalem
        command:
            [
                'ash',
                '-c',
                'npm install pm2 -g && cd /app/ && yarn install --production && pm2 start && pm2 logs -f',
            ]
