{
 "title": "Update alsdle via API",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sensor_id AS metric,\n  value AS \"value\"\nFROM measurements\nWHERE\n  $__timeFilter(ts) AND\n  sensor_id = 'SOL-38:2b:78:3:ec:df/lux'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Temperture",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sensor_id AS metric,\n  value AS \"temperature\"\nFROM measurements\nWHERE\n  $__timeFilter(ts) AND\n  sensor_id = 'SOL-38:2b:78:3:ec:df/temp'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sensor_id AS metric,\n  value AS \"value\"\nFROM measurements\nWHERE\n  $__timeFilter(ts) AND\n  sensor_id = 'SOL-38:2b:78:3:ec:df/humidity'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Lux",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sensor_id AS metric,\n  value AS \"value\"\nFROM measurements\nWHERE\n  $__timeFilter(ts) AND\n  sensor_id = 'SOL-38:2b:78:3:ec:df/lux'\nORDER BY ts"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sensor_id AS metric,\n  value AS \"value\"\nFROM measurements\nINNER JOIN sensors ON sensors.id = sensor_id\nWHERE\n  $__timeFilter(ts) AND\n  sensor_id = 'SOL-38:2b:78:3:ec:df/co2'\nORDER BY ts"
    }
   ]
  }
 ]
}